### ISSUE TITLE
password?

### ISSUE THREAD

**Issue by lovetoburnswhen** [totalhack/zillion-web#1]
What are the login credentials for the demo site at https://zillionweb.totalhack.org/login ?

**Comment by totalhack** [comment]
Hey there, that demo site is still up but outdated at the moment as I haven't had a chance to deploy some bug fixes over there. The data of the demo warehouses also isn't being updated. I actually had removed it from the README recently for that reason. 

That said, if you still want to poke around with those caveats in mind, the demo login is:

demouser@example.com
demopass
